apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rg-aks-example-dev
  labels:
    azure.aks.io/resource-group-example: rg-aks-example-dev
spec:
  forProvider:
    location: eastus2

---

apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  labels:
    azure.aks.io/aks-example: aks-example
  name: lab-idp-aks
spec:
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
    nodeResourceGroup: rg-aks-nodes-example-dev
    dnsPrefix: exampleaks1
    identity:
      - type: SystemAssigned
    location: East US
    resourceGroupNameSelector:
      matchLabels:
        azure.aks.io/resource-group-example: rg-aks-example-dev
    tags:
      Environment: Develop